---
- name: copy server side staking cli tool to {{ ansible_user }} home directory
  hosts:
    geth

  vars:

#    staking_deposit_cli: "/path/to/stakingdepositcli"     

  tasks:
    - name: copy current server side staking cli executable  
      ansible.builtin.unarchive:
        src: "{{ staking_deposit_cli }}"
        remote_src: no
        dest: '/home/{{ ansible_user }}'
        owner: '{{ ansible_user }}'
      become: yes
...
