---
# 25 nov 2023 rehaul, replace existing serial tasks with loops.

  - name: groups present
    ansible.builtin.group:
      name: "{{ item }}"
      state: present
    become: yes
    loop: 
        - lighthousebeacon
        - goeth
 
# NB the root group was added to stop ansible borking, original just provisioned a root acc, no group details
  - name: accounts present
    ansible.builtin.user:
      name: "{{ item.name }}"
      groups: "{{ item.groups }}"
      comment: "{{ item.comment }}"
      shell: "/bin/false"
      create_home: no
    loop:
        - { name: 'goeth', groups: 'goeth', comment: 'acc for geth exe layer'}
        - { name: 'lighthousebeacon', groups: 'lighthousebeacon', comment: 'acc for lighthouse validator service' }
    become: yes

  - name: check folders in place, create if needed
    ansible.builtin.file:
      path: "{{ item.path }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      state: directory
    loop:      
      - { path: '/var/lib/goethereum', owner: 'goeth', group: 'goeth', state: directory }
      - { path: '/var/lib/lighthouse', owner: 'lighthousebeacon', group: 'lighthousebeacon', state: 'directory' }
      - { path: '/var/lib/lighthouse/validators', owner: 'lighthousevalidator', state: 'directory' ,group: 'lighthousevalidator', mode: '0700' }
      - { path: '/var/lib/ethereum', owner: 'root', group: 'root', state: directory }
    become: yes

  - name: geth PPA - ppa:ethereum/ethereum added
    ansible.builtin.apt_repository:
      repo: ppa:ethereum/ethereum
    become: true

  - name: Latest geth and other packages installed from PPA
    apt:
      update_cache: yes  
      pkg: 
      - software-properties-common
      - geth
      - ccze
    become: true

  - name: copy services
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: no
      owner: root
      mode: 0755
    become: yes
    loop: 
        - { src: '{{ lighthouse_service }}', dest: '/etc/systemd/system/lighthousevalidator.service' }
        - { src: '{{ lighthouse_validator_service }}', dest: '/etc/systemd/system/lighthousevalidator.service' }
        - { src: '{{ geth_service }}', dest: '/etc/systemd/system/geth.service' }

  - name: enable services
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    become: yes
    loop: 
      - geth.service
      - lighthousebeacon.service
      - lighthousevalidator.service
...
