---
# This script should build ethereum nodes without validators, just comment out all the validator steps below
# 25 nov 2023 rehaul, replace existing serial tasks with loops.
# NB the root group was added to stop ansible borking, original just provisioned a root acc, no group details



  - name: groups present
    ansible.builtin.group:
      name: "{{ item }}"
      state: present
    become: yes
    loop: 
        - lighthousebeacon
        - goeth
 
  - name: accounts present
    ansible.builtin.user:
      name: "{{ item.name }}"
      groups: "{{ item.groups }}"
      comment: "{{ item.comment }}"
            #      shell: "/bin/false"
            #    create_home: no
    loop:
        - { name: 'goeth', groups: 'goeth', comment: 'acc for geth exe layer'}
        - { name: 'lighthousebeacon', groups: 'lighthousebeacon', comment: 'acc for lighthouse validator service' }
    become: yes

  - name: check folders in place, create if needed
    ansible.builtin.file:
      path: "{{ item.path }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      state: directory
    loop:      
      - { path: '/var/lib/goethereum', owner: 'goeth', group: 'goeth', state: directory }
      - { path: '/var/lib/lighthouse', owner: 'lighthousebeacon', group: 'lighthousebeacon', state: 'directory' }
      - { path: '/var/lib/lighthouse/validators', owner: 'lighthousevalidator', state: 'directory' ,group: 'lighthousevalidator', mode: '0700' }
      - { path: '/var/lib/ethereum', owner: 'root', group: 'root', state: directory }
    become: yes

  - name: geth PPA - ppa:ethereum/ethereum added
    ansible.builtin.apt_repository:
      repo: ppa:ethereum/ethereum
    become: true

  - name: Latest geth and other packages installed from PPA
    apt:
      update_cache: yes  
      pkg: 
      - software-properties-common
      - geth
      - ccze
    become: true

  - name: copy lighthouse.service 
    ansible.builtin.copy:
      src: "{{ lighthouse_service }}"
      remote_src: no
      dest: '/etc/systemd/system/lighthousebeacon.service'
      owner: root
      mode: 0755
    become: yes

  - name: copy lighthousevalidator.service 
    ansible.builtin.copy:
      src: "{{ lighthouse_validator_service }}"
      remote_src: no
      dest: '/etc/systemd/system/lighthousevalidator.service'
      owner: root
      mode: 0755
    become: yes

  - name: copy geth.service 
    ansible.builtin.copy:
      src: "{{ geth_service }}"
      remote_src: no
      dest: '/etc/systemd/system/geth.service'
      owner: root
      mode: 0755
    become: yes

  - name: copy current server side lighthouse executable to bin dir  
    ansible.builtin.copy:
      src: "{{ lighthouse_exe }}"
      remote_src: no
      dest: '/usr/local/bin/lighthouse'
      owner: root
      mode: 0755
    become: yes

# Uncomment this play to copy the staking deposit cli tool to the host, alternately
# you could run it on your ansible management host and scp the files across 
# If you run it change the dest: folder below to the needful
#
#  - name: copy current server side staking cli executable  
#    ansible.builtin.unarchive:
#      src: "{{ staking_deposit_cli }}"
#      remote_src: no
#      dest: '/home/cia'
#      owner: cia
#    become: yes

  - name: geth service enable
    ansible.builtin.systemd:
      name: geth.service
      state: started
      enabled: yes
    become: yes

  - name: lighthouse service enable
    ansible.builtin.systemd:
      name: lighthousebeacon.service
      state: started
      enabled: yes
    become: yes

  - name: lighthouse validator service enable
    ansible.builtin.systemd:
      name: lighthousevalidator.service
      state: started
      enabled: yes
    become: yes

...
